### ISSUE TITLE
Enormous Code Error

### ISSUE THREAD

**Issue by alexbruce** [concurlabs/SwiftyConcur#30]
Dear ConcurLabs,
Once I have installed the pod to my Xcode project, when I run the simulator, I am greeting with countless errors in my debugger. I am wondering if this is a problem with your code or with my Xcode.
I have tried updating cocoa pods but no success as of yet.

**Comment by brennick** [comment]
@alexbruce could you post a snippet of the errors you are getting?

**Comment by alexbruce** [comment]
The issue was resolved by downgrading my Xcode version to 6.4 and thus downgrading my version of swift.
The issue here was that this repository wasn't compatible with swift 2, at least in my case anyway.
Thank you.

**Comment by brennick** [comment]
Looking into compatibility issues.

**Comment by brennick** [comment]
Using Version 7.3.1 of Xcode the project builds fine for me and is using Swift 2, could you check your Podfile.lock and let me know what version of SwiftyConcur you have installed @alexbruce? The latest is 0.1.1.

**Comment by alexbruce** [comment]
I was using Xcode 7.2.1 so that must have been the issue. Thank you for your helpfulness :)
- Alex
